### ISSUE TITLE
Missing LICENSE

### ISSUE THREAD

**Issue by zynga-jpetersen** [webrender/slack-wordle#3]
Greetings,

This is cool and I'd like to mess around with it for non-work related purposes, but it doesn't have a license, so I cant even look at it.

But thanks for making this and putting it out there.

Also FYI, NYT does have an api it looks like to get previous words, so I think it would be easy to update your bot to use that.

https://www.nytimes.com/svc/wordle/v2/{YYYY-MM-DD}.json

**Comment by webrender** [comment]
Hey there, I've gone ahead and added a license file to this repository if you still wish to use it.  I'm unsure of how compatible it still is with NYT Wordle.
